import "./globals.css";
import MainNavbarComponent from "../components/main-navbar-component";

export const metadata = {
  title: "Next Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-[120rem] mx-auto bg-lightCol1 text-lightCol2 dark:bg-darkCol1 dark:text-darkCol2">
        <MainNavbarComponent />
        <main className="overflow-auto h-[calc(100vh-4rem)]">{children}</main>
      </body>
    </html>
  );
}
